#!/bin/bash

unset LD_PRELOAD
unset LD_LIBRARY_PATH

BASEDIR="$(pwd)"

export DOORSTOP_ENABLED="1"
export DOORSTOP_TARGET_ASSEMBLY="BepInEx/core/BepInEx.Preloader.dll"
export DOORSTOP_IGNORE_DISABLED_ENV="0"
export DOORSTOP_MONO_DLL_SEARCH_PATH_OVERRIDE=""
export DOORSTOP_MONO_DEBUG_ENABLED="0"
export DOORSTOP_MONO_DEBUG_ADDRESS="127.0.0.1:10000"
export DOORSTOP_MONO_DEBUG_SUSPEND="0"
export DOORSTOP_CLR_RUNTIME_CORECLR_PATH=".so"
export DOORSTOP_CLR_CORLIB_DIR=""

export LD_LIBRARY_PATH="${BASEDIR}"
export LD_PRELOAD="libdoorstop.so"

./AShortHike.x86_64
